// Generated automatically by nearley, version 2.19.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

let variables = {};
const moo = require("moo");
const trim = token => {token.trim()};
const string = token => {
    var regex = /\[\[([\w:\.]+)=([\s\S](?!\]\]))+ ?\]\]/ // Same regexp but with a capture group
    let match = token.match(regex)
    return {string: match[2], name: match[1]};
}
const optString = token => {
    var regex = /"([\s\S]*)=([a-z '_A-Z0-9]*)"/;
    let match = token.match(regex);
    if (match && match[1] && match[2]) {
        return {string: match[2], name: match[1]}
    } else {
        return {string: ' ', name: ' '}
    }
}
const lexer = moo.compile({
    _:      /[ \t]+/,
    NUMBER:  /0|[1-9][0-9]*/,
    EMPTY_STRING: /" "/,
    OPT_STRING:  {match: /"[\w:\.]+=[a-z '_A-Z0-9]+"/, value: optString},
    PROMPT_STRING:  {match: /\[\[[\w:\.]+=(?:[\s\S](?!\]\]))+ ?\]\]/, value: string},
    LPAREN:  {match: /\(/, value: trim},
    RPAREN:  {match: /\)/, value: trim},
    LBRACE:  {match: /\{/, value: trim},
    RBRACE:  {match: /\}[ \t]?/, value: trim},
    TERMINAL: {match: /terminal/, value: trim},
    COLON: {match: /\:/, value: trim},
    KEYWORD: {match: [/notext/, /goto/, /setlocal/, /prompt/], value:trim},
    OPTIONS: {match: [/options/], value: trim},
    WHEN: {match: /when/, value: trim},
    NOT: [/not/],
    AND: [/and/],
    SHORT: [/short/],
    NEXT: [/next/],
    SET: [/set/],
    OR: [/or/],
    NL:      { match: /\n/, lineBreaks: true },
    IDENT: { match: /[a-z_A-Z0-9]+/, value: trim},
    INSTRUCTION: ['notext']
});
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "main$ebnf$1", "symbols": []},
    {"name": "main$ebnf$1$subexpression$1", "symbols": ["stmt"]},
    {"name": "main$ebnf$1$subexpression$1", "symbols": ["exp"]},
    {"name": "main$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "main$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "main$ebnf$1", "symbols": ["main$ebnf$1", "main$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "main", "symbols": ["main$ebnf$1"]},
    {"name": "stmt", "symbols": [(lexer.has("TERMINAL") ? {type: "TERMINAL"} : TERMINAL), (lexer.has("_") ? {type: "_"} : _), (lexer.has("WHEN") ? {type: "WHEN"} : WHEN), (lexer.has("_") ? {type: "_"} : _), "exp", "termblock"]},
    {"name": "termblock$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "termblock$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termblock$ebnf$1", "symbols": ["termblock$ebnf$1$subexpression$1"]},
    {"name": "termblock$ebnf$1$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "termblock$ebnf$1$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termblock$ebnf$1", "symbols": ["termblock$ebnf$1", "termblock$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "termblock$ebnf$2$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "termblock$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termblock$ebnf$2", "symbols": ["termblock$ebnf$2$subexpression$1"]},
    {"name": "termblock$ebnf$2$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "termblock$ebnf$2$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termblock$ebnf$2", "symbols": ["termblock$ebnf$2", "termblock$ebnf$2$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "termblock$ebnf$3", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termblock$ebnf$3", "symbols": ["termblock$ebnf$3", (lexer.has("NL") ? {type: "NL"} : NL)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "termblock", "symbols": [(lexer.has("LBRACE") ? {type: "LBRACE"} : LBRACE), "termblock$ebnf$1", "termstmt", "termblock$ebnf$2", (lexer.has("RBRACE") ? {type: "RBRACE"} : RBRACE), "termblock$ebnf$3"]},
    {"name": "termstmt$ebnf$1", "symbols": []},
    {"name": "termstmt$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "termstmt$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "termstmt$ebnf$1", "symbols": ["termstmt$ebnf$1", "termstmt$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "termstmt$ebnf$2", "symbols": []},
    {"name": "termstmt$ebnf$2$subexpression$1", "symbols": ["action"]},
    {"name": "termstmt$ebnf$2", "symbols": ["termstmt$ebnf$2", "termstmt$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "termstmt", "symbols": ["action", "termstmt$ebnf$1", "termstmt$ebnf$2"]},
    {"name": "action", "symbols": [(lexer.has("KEYWORD") ? {type: "KEYWORD"} : KEYWORD)]},
    {"name": "action$ebnf$1", "symbols": []},
    {"name": "action$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$1", "symbols": ["action$ebnf$1", "action$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action", "symbols": [(lexer.has("KEYWORD") ? {type: "KEYWORD"} : KEYWORD), (lexer.has("COLON") ? {type: "COLON"} : COLON), (lexer.has("_") ? {type: "_"} : _), (lexer.has("IDENT") ? {type: "IDENT"} : IDENT), "action$ebnf$1"]},
    {"name": "action$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$2$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$2", "symbols": ["action$ebnf$2$subexpression$1"]},
    {"name": "action$ebnf$2$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$2$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$2", "symbols": ["action$ebnf$2", "action$ebnf$2$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action", "symbols": [(lexer.has("KEYWORD") ? {type: "KEYWORD"} : KEYWORD), (lexer.has("COLON") ? {type: "COLON"} : COLON), (lexer.has("_") ? {type: "_"} : _), (lexer.has("PROMPT_STRING") ? {type: "PROMPT_STRING"} : PROMPT_STRING), "action$ebnf$2"]},
    {"name": "action$ebnf$3", "symbols": []},
    {"name": "action$ebnf$3$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$3$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$3", "symbols": ["action$ebnf$3", "action$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action", "symbols": ["set_opt", "action$ebnf$3"]},
    {"name": "action$ebnf$4", "symbols": []},
    {"name": "action$ebnf$4$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$4", "symbols": ["action$ebnf$4", "action$ebnf$4$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action$ebnf$5", "symbols": []},
    {"name": "action$ebnf$5$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$5$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$5", "symbols": ["action$ebnf$5", "action$ebnf$5$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action$ebnf$6", "symbols": ["options_stmt"]},
    {"name": "action$ebnf$6", "symbols": ["action$ebnf$6", "options_stmt"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action$ebnf$7", "symbols": []},
    {"name": "action$ebnf$7$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "action$ebnf$7$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "action$ebnf$7", "symbols": ["action$ebnf$7", "action$ebnf$7$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action", "symbols": [(lexer.has("OPTIONS") ? {type: "OPTIONS"} : OPTIONS), (lexer.has("COLON") ? {type: "COLON"} : COLON), "action$ebnf$4", (lexer.has("LBRACE") ? {type: "LBRACE"} : LBRACE), "action$ebnf$5", "action$ebnf$6", (lexer.has("RBRACE") ? {type: "RBRACE"} : RBRACE), "action$ebnf$7"]},
    {"name": "options_stmt$ebnf$1", "symbols": []},
    {"name": "options_stmt$ebnf$1", "symbols": ["options_stmt$ebnf$1", "options_conf"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "options_stmt", "symbols": ["def_opt", "options_stmt$ebnf$1"]},
    {"name": "options_stmt$ebnf$2", "symbols": []},
    {"name": "options_stmt$ebnf$2", "symbols": ["options_stmt$ebnf$2", "options_conf"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "options_stmt", "symbols": [(lexer.has("EMPTY_STRING") ? {type: "EMPTY_STRING"} : EMPTY_STRING), (lexer.has("_") ? {type: "_"} : _), "options_stmt$ebnf$2"]},
    {"name": "options_conf$ebnf$1", "symbols": []},
    {"name": "options_conf$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "options_conf$ebnf$1", "symbols": ["options_conf$ebnf$1", "options_conf$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "options_conf", "symbols": ["short_opt", "options_conf$ebnf$1"]},
    {"name": "options_conf$ebnf$2", "symbols": []},
    {"name": "options_conf$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "options_conf$ebnf$2", "symbols": ["options_conf$ebnf$2", "options_conf$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "options_conf", "symbols": ["next_opt", "options_conf$ebnf$2"]},
    {"name": "options_conf$ebnf$3", "symbols": []},
    {"name": "options_conf$ebnf$3$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "options_conf$ebnf$3", "symbols": ["options_conf$ebnf$3", "options_conf$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "options_conf", "symbols": ["set_opt", "options_conf$ebnf$3"]},
    {"name": "def_opt$ebnf$1", "symbols": []},
    {"name": "def_opt$ebnf$1", "symbols": ["def_opt$ebnf$1", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "def_opt", "symbols": [(lexer.has("OPT_STRING") ? {type: "OPT_STRING"} : OPT_STRING), "def_opt$ebnf$1"]},
    {"name": "short_opt$ebnf$1", "symbols": []},
    {"name": "short_opt$ebnf$1", "symbols": ["short_opt$ebnf$1", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "short_opt$ebnf$2", "symbols": []},
    {"name": "short_opt$ebnf$2", "symbols": ["short_opt$ebnf$2", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "short_opt", "symbols": [(lexer.has("SHORT") ? {type: "SHORT"} : SHORT), (lexer.has("COLON") ? {type: "COLON"} : COLON), "short_opt$ebnf$1", (lexer.has("OPT_STRING") ? {type: "OPT_STRING"} : OPT_STRING), "short_opt$ebnf$2"]},
    {"name": "next_opt$ebnf$1", "symbols": []},
    {"name": "next_opt$ebnf$1", "symbols": ["next_opt$ebnf$1", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "next_opt$ebnf$2", "symbols": []},
    {"name": "next_opt$ebnf$2", "symbols": ["next_opt$ebnf$2", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "next_opt", "symbols": [(lexer.has("NEXT") ? {type: "NEXT"} : NEXT), (lexer.has("COLON") ? {type: "COLON"} : COLON), "next_opt$ebnf$1", (lexer.has("IDENT") ? {type: "IDENT"} : IDENT), "next_opt$ebnf$2"]},
    {"name": "set_opt$ebnf$1", "symbols": []},
    {"name": "set_opt$ebnf$1", "symbols": ["set_opt$ebnf$1", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "set_opt$ebnf$2", "symbols": []},
    {"name": "set_opt$ebnf$2", "symbols": ["set_opt$ebnf$2", (lexer.has("_") ? {type: "_"} : _)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "set_opt", "symbols": [(lexer.has("SET") ? {type: "SET"} : SET), (lexer.has("COLON") ? {type: "COLON"} : COLON), "set_opt$ebnf$1", (lexer.has("IDENT") ? {type: "IDENT"} : IDENT), "set_opt$ebnf$2"]},
    {"name": "exp$ebnf$1", "symbols": []},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1", "symbols": ["exp$ebnf$1$subexpression$1$ebnf$1$subexpression$1"]},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "exp$ebnf$1$subexpression$1$ebnf$1", "symbols": ["exp$ebnf$1$subexpression$1$ebnf$1", "exp$ebnf$1$subexpression$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "exp$ebnf$1$subexpression$1", "symbols": [(lexer.has("OR") ? {type: "OR"} : OR), "exp$ebnf$1$subexpression$1$ebnf$1", "term"]},
    {"name": "exp$ebnf$1", "symbols": ["exp$ebnf$1", "exp$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "exp", "symbols": ["term", "exp$ebnf$1"]},
    {"name": "term$ebnf$1", "symbols": []},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1", "symbols": ["term$ebnf$1$subexpression$1$ebnf$1$subexpression$1"]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1", "symbols": ["term$ebnf$1$subexpression$1$ebnf$1", "term$ebnf$1$subexpression$1$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "term$ebnf$1$subexpression$1", "symbols": [(lexer.has("AND") ? {type: "AND"} : AND), "term$ebnf$1$subexpression$1$ebnf$1", "factor"]},
    {"name": "term$ebnf$1", "symbols": ["term$ebnf$1", "term$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "term", "symbols": ["factor", "term$ebnf$1"]},
    {"name": "factor$ebnf$1", "symbols": []},
    {"name": "factor$ebnf$1$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "factor$ebnf$1$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "factor$ebnf$1", "symbols": ["factor$ebnf$1", "factor$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "factor", "symbols": [(lexer.has("IDENT") ? {type: "IDENT"} : IDENT), "factor$ebnf$1"]},
    {"name": "factor$ebnf$2$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "factor$ebnf$2$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "factor$ebnf$2", "symbols": ["factor$ebnf$2$subexpression$1"]},
    {"name": "factor$ebnf$2$subexpression$2", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "factor$ebnf$2$subexpression$2", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "factor$ebnf$2", "symbols": ["factor$ebnf$2", "factor$ebnf$2$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "factor", "symbols": [(lexer.has("NOT") ? {type: "NOT"} : NOT), "factor$ebnf$2", "factor"]},
    {"name": "factor$ebnf$3", "symbols": []},
    {"name": "factor$ebnf$3$subexpression$1", "symbols": [(lexer.has("_") ? {type: "_"} : _)]},
    {"name": "factor$ebnf$3$subexpression$1", "symbols": [(lexer.has("NL") ? {type: "NL"} : NL)]},
    {"name": "factor$ebnf$3", "symbols": ["factor$ebnf$3", "factor$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "factor", "symbols": [(lexer.has("LPAREN") ? {type: "LPAREN"} : LPAREN), "exp", (lexer.has("RPAREN") ? {type: "RPAREN"} : RPAREN), "factor$ebnf$3"]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
