 
worldGlobals.CutScene(thisScript, IntroChapter, sndFX, sndVoice, function()
  --StartPrecachingSequence(thisScript, tpsTexturePrecache)
  --EnableMovieExporting()
  --SetMovieSegmentDesc("Intro")

  if genvIsTrialVersion() then
    ttpPublicTestLogo:Appear()
  else
    ttpLogo:Appear()
  end
    
  Wait(Delay(1))
  
  -- croteam logo  
  RunAsync(function()
    BigRgbAnimator:StartAnimation("Off")
    CroteamLogoFull:Disappear()
    CroteamLogoTranslucent:Appear()
    Wait(Delay(2.1))
    BigRgbAnimator:StartAnimation("On")
    Wait(Delay(0.1))
    BigRgbAnimator:StartAnimation("Off")
    Wait(Delay(0.39))
    BigRgbAnimator:StartAnimation("On")
    Wait(Delay(0.1))
    BigRgbAnimator:StartAnimation("Off")
    CroteamLogoFull:Appear()
    CroteamLogoTranslucent:Disappear()
    Wait(Delay(0.75))
    CroteamLogoFull:Disappear()
    CroteamLogoTranslucent:Appear()
  end)
  
  StreaksCroteam:StartAnimation("TurningOff")
  RGBCroteam:StartAnimation("Living")
  CameraCroteam:PlayAnimWait("Default")
  CroteamLogoAppearAnimator:StartAnimation("Appearing")
  CroteamLogoStreaksAnimator:StartAnimation("TurningOff")
  Wait(Delay(4))
  CroteamLogoAppearAnimator:StartAnimation("FastOff")
  LightnessAndRgbAnimator:StartAnimation("TurningOn")
  Wait(Delay(1.5))

  -- devolver logo
  LogoApearAnimator:StartAnimation("Off")
  FlareAnimator:StartAnimation("Off")
  FlareBorder1Animator:StartAnimation("Off")
  FlareBorder2Animator:StartAnimation("Off")
  FlareDigitalAnimator:StartAnimation("Off")
  BlurAnimator:StartAnimation("Off")
  BloomAnimator:StartAnimation("Bloom")
  LogoApearAnimator:StartAnimation("Appearing")
  Mover:PlayAnim("Default")
  RunAsync(function()
    Particles:Start()
    Wait(Delay(1.5))
    Particles:DisableEmitting()
  end)
  RunAsync(function()
    Wait(Delay(2.0)) 
    StreaksAnimator:StartAnimation("TurningOff")
  end)
  
  RunAsync(function()
    Wait(Delay(1.4))
    FlareBorder1Animator:StartAnimation("Pulsating")
    FlareBorder2Animator:StartAnimation("Pulsating")
    FlareDigitalAnimator:StartAnimation("Pulsating")
    ParticlesBorder1:Start()
    ParticlesBorder2:Start()
    ParticlesDigital:Start()
    Wait(Delay(0.5))
    ParticlesBorder1:DisableEmitting()
    ParticlesBorder2:DisableEmitting()
    ParticlesDigital:DisableEmitting()
  end)
  
  RunAsync(function()
    FlareAnimator:StartAnimation("Pulsating")
    Wait(Delay(1.4))
    MoverBorder1:PlayAnim("Default")
    MoverBorder2:PlayAnim("Default")
    MoverDigital:PlayAnim("Default")
    Wait(Delay(0.3))
    FlareAnimator:StartAnimation("Off")
    FlareBorder1Animator:StartAnimation("Off")
    FlareBorder2Animator:StartAnimation("Off")
    FlareDigitalAnimator:StartAnimation("Off")
  end)
  Wait(CameraDevolver:PlayAnimWait("Default"))
  
  -- Talos logo
  RunAsync(function()
    --Wait(Delay(1))
    TalosStreaksAnimator:StartAnimation("TurningOff")
  end)
  
  TalosLogoSpotlightMover:PlayAnim("Default")

  Wait(CameraTalos:PlayAnimWait("TalosLogo"))    
  --StopPrecachingSequence(thisScript)

  --StopMovieExporting()
  
  -- temp delay to prevent crash when exporting frames for movie
  --Wait(Delay(1))
end)
EndOfGame:Start()
